CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
	id uuid DEFAULT uuid_generate_v4(),
    first_name VARCHAR(250),
    last_name VARCHAR(250),
    email VARCHAR(250) NOT NULL UNIQUE,
    phone_number VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR(250) NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY(id)
);